- name: Deploy Laravel App
  hosts: web
  become: yes
  gather_facts: no

  tasks:
    - name: Bootstrap remote Python dependencies
      raw: apt-get update -y && apt-get install -y python3-six rsync

    - name: Sync project to server
      synchronize:
        src: "{{ workspace }}/"
        dest: /var/www/html/pheaktra/
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"

    - name: Install Composer dependencies
      command: composer install
      args:
        chdir: /var/www/html/pheaktra

    - name: Generate Laravel key
      command: php artisan key:generate
      args:
        chdir: /var/www/html/pheaktra

    - name: Run migrations
      command: php artisan migrate --force
      args:
        chdir: /var/www/html/pheaktra